### model
model_name_or_path: /model/huggingface/hub/Qwen2.5-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: critic_train_m2w
template: qwen2_vl
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
media_dir: ''

### output
output_dir: /your/path/to/output
logging_steps: 10
save_steps: 512
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

